name: bondly
description: "Bondly - Real connections through voice and video"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  # Calling
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  # Storage & Networking
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
