// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG8CL0l2fTzMA_Wtk96RT6NVvIrCRCh5o',
    appId: '1:359983887164:web:852eb7e301cb495c56e439',
    messagingSenderId: '359983887164',
    projectId: 'bondly-app-dev-2026-677e5',
    authDomain: 'bondly-app-dev-2026-677e5.firebaseapp.com',
    storageBucket: 'bondly-app-dev-2026-677e5.firebasestorage.app',
    measurementId: 'G-JRWHCT0ZK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZmFk0Os8fO8VLFTDQYHq2dpA10awM4s',
    appId: '1:359983887164:android:0ec245fc32f2997556e439',
    messagingSenderId: '359983887164',
    projectId: 'bondly-app-dev-2026-677e5',
    storageBucket: 'bondly-app-dev-2026-677e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJpU0uh5s-xBLLCtfy4Xz_ypd7ZVfMAk',
    appId: '1:359983887164:ios:a599518fe0d6a5f156e439',
    messagingSenderId: '359983887164',
    projectId: 'bondly-app-dev-2026-677e5',
    storageBucket: 'bondly-app-dev-2026-677e5.firebasestorage.app',
    iosBundleId: 'com.example.bondly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJpU0uh5s-xBLLCtfy4Xz_ypd7ZVfMAk',
    appId: '1:359983887164:ios:a599518fe0d6a5f156e439',
    messagingSenderId: '359983887164',
    projectId: 'bondly-app-dev-2026-677e5',
    storageBucket: 'bondly-app-dev-2026-677e5.firebasestorage.app',
    iosBundleId: 'com.example.bondly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG8CL0l2fTzMA_Wtk96RT6NVvIrCRCh5o',
    appId: '1:359983887164:web:0a6936a770db155e56e439',
    messagingSenderId: '359983887164',
    projectId: 'bondly-app-dev-2026-677e5',
    authDomain: 'bondly-app-dev-2026-677e5.firebaseapp.com',
    storageBucket: 'bondly-app-dev-2026-677e5.firebasestorage.app',
    measurementId: 'G-DX55FRETYG',
  );
}
